project:
  type: website
  output-dir: docs

website:
  title: "Vishal Bakshi's Blog"
  site-url: https://vishalbakshi.github.io/blog
  description: "Machine Learning blog by Vishal Bakshi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: eagles.scss
    css: styles.css
    toc: true
  

