project:
  type: website
  output-dir: docs

website:
  title: "vishal bakshi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: eagles.scss
    css: styles.css
    toc: true



