---
title: "About"
---

## hi.

my name is vishal bakshi. i'm a data analyst at the City of Portland. i haven't blogged in a couple of years and recently have had the desire to do so again so here i am. 

## things i like consistently

hip hop, yoga, lifting free weights, resistance bands, coding, writing, reading, cold weather, philadelphia eagles, la lakers.

## what i'm currently reading

check out my [currently reading](https://www.goodreads.com/review/list/118261002-vishal-bakshi?ref=nav_mybooks&shelf=currently-reading) list on goodreads.

## what i'm working on consistently
- observing my thoughts, emotions and behaviors.
- making and practicing hip hop music.
- learning about how and why our society is structured the way it is.

## what i'm currently working on as well
- learning spanish while watching sherlock holmes (the bbc version with cumberbatch).
- exploring NFL play-by-play data.
- learning how to make good chicken wings (made them the first time on 2/4/23 and they were a 5/10. hoping to get to a 10/10 by the 2023 NFL season).

