<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vishal Bakshi">
<meta name="dcterms.date" content="2024-02-29">
<meta name="description" content="A recap of what and how I did on the Multi-Class Prediction of Obesity Risk Kaggle Competition.">

<title>Vishal Bakshi’s Blog - Recap: My First Live Kaggle Competition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Vishal Bakshi’s Blog</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#live-competition-approach" id="toc-live-competition-approach" class="nav-link" data-scroll-target="#live-competition-approach">Live Competition Approach</a></li>
  <li><a href="#why-did-i-score-so-low" id="toc-why-did-i-score-so-low" class="nav-link" data-scroll-target="#why-did-i-score-so-low">Why Did I Score So Low?</a></li>
  <li><a href="#post-competition-analysis" id="toc-post-competition-analysis" class="nav-link" data-scroll-target="#post-competition-analysis">Post-Competition Analysis</a></li>
  <li><a href="#final-thoughts" id="toc-final-thoughts" class="nav-link" data-scroll-target="#final-thoughts">Final Thoughts</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Recap: My First Live Kaggle Competition</h1>
  <div class="quarto-categories">
    <div class="quarto-category">fastai</div>
    <div class="quarto-category">kaggle competition</div>
    <div class="quarto-category">machine learning</div>
  </div>
  </div>

<div>
  <div class="description">
    A recap of what and how I did on the Multi-Class Prediction of Obesity Risk Kaggle Competition.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Vishal Bakshi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 29, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>After submitting predictions for a couple of closed Kaggle competitions as part of the fastai course, I participated in my first live Kaggle competition, Multi-Class Prediction of Obesity Risk. I ended up in the bottom 17% of the Private Leaderboard, ranking 2960 out of 3587. My Private ranking was 281 spots lower than my Public ranking (yikes!).</p>
<p>You can see my live competition notebook <a href="https://www.kaggle.com/code/vishalbakshi/multi-class-prediction-of-obesity-risk-fastai">here</a> and my post-competition notebook <a href="https://www.kaggle.com/code/vishalbakshi/post-competition-hyperparameter-sweep">here</a>.</p>
<p>In this blog post, I’ll recap my experience in this competition, and what I took away from it.</p>
<p>My main goal right now is learning, learning, learning. That being said, getting 10+ upvotes and 200+ views (probably 50 of them were mine) on my <strong>first bronze notebook</strong> felt <em>AWESOME</em>. I am already excited to try to get another bronze notebook. I also would like to get into the top 50% on the final Private Leaderboard for any live competition (including the playground series) this year.</p>
</section>
<section id="live-competition-approach" class="level2">
<h2 class="anchored" data-anchor-id="live-competition-approach">Live Competition Approach</h2>
<p>I decided to strictly follow the fastai textbook’s <a href="https://github.com/fastai/fastbook/blob/master/09_tabular.ipynb">Chapter 9 approach</a> to tabular data prediction using a Random Forest, Neural Net, and ensemble of both. I wanted to understand how each step affected the Public score.</p>
<p>In the end, I did 10 versions or iterations of my notebook that are summarized in the table below:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Version</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Private Score</th>
<th style="text-align: left;">Public Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">quick and dirty RF</td>
<td style="text-align: left;">0.89378</td>
<td style="text-align: left;">0.89585</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">ordered ordinal columns</td>
<td style="text-align: left;">0.89495</td>
<td style="text-align: left;">0.89559</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">high importance cols only</td>
<td style="text-align: left;">0.89342</td>
<td style="text-align: left;">0.8945</td>
</tr>
<tr class="even">
<td style="text-align: left;">4*</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">rf with id col removed</td>
<td style="text-align: left;">0.89116</td>
<td style="text-align: left;">0.88728</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">neural net</td>
<td style="text-align: left;">0.8675</td>
<td style="text-align: left;">0.86452</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7^^</td>
<td style="text-align: left;">rf nn ensemble</td>
<td style="text-align: left;">0.8861</td>
<td style="text-align: left;">0.88656</td>
</tr>
<tr class="even">
<td style="text-align: left;">8**</td>
<td style="text-align: left;">increase number of trees</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">–</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9^^</td>
<td style="text-align: left;">embedding-rf nn ensemble</td>
<td style="text-align: left;">0.88538</td>
<td style="text-align: left;">0.89053</td>
</tr>
</tbody>
</table>
<p>*In version 4, I was planning to remove redundant features, but none of them were redundant so I didn’t re-train my Random Forest and didn’t submit predictions.</p>
<p>**In version 8, I was planning on increasing the number of trees in my Random Forest but that didn’t improve the validation set accuracy so I didn’t submit any predictions.</p>
<p>^^Selected for final leaderboard score (0.88610)</p>
</section>
<section id="why-did-i-score-so-low" class="level2">
<h2 class="anchored" data-anchor-id="why-did-i-score-so-low">Why Did I Score So Low?</h2>
<p>It’s interesting to note that the highest Private scores were my Random Forest with ordinal columns set (0.89495) and my quick and dirty Random Forest (0.89378).</p>
<p>I think the reason that the chapter’s strategies did not improve my score is because those strategies were not solely meant to improve accuracy—they were also meant to simplify the model and dataset for better interpretability. However, this dataset was small to begin with (17 independent variables) and removing low importance variables and the <code>id</code> column brought that down to 12 columns. Contrast that with the textbook where we went from about 70 columns to 20.</p>
<p>Jeremy has also mentioned throughout the course that getting that final 1% or 2% of accuracy for a Kaggle score is generally when you have to start fussing with the details. Simplifying and understanding a model (how different columns and rows of the dataset are used/affected by it) is a different problem to solve than getting 2% more to win a Kaggle competition.</p>
<p>I was surprised that the neural nets performed so poorly, even in the public score. I was banking on the ensemble being more flexible than the Random Forest, and expected it to result in a higher final Private score.</p>
<p>I haven’t looked at anyone else’s notebooks yet, I plan on doing that next, but I did see quite a few XGBoost-related notebook titles, and my understanding is that model performs better than Random Forests. Something I’ll practice modeling in the next tabular competition I join.</p>
</section>
<section id="post-competition-analysis" class="level2">
<h2 class="anchored" data-anchor-id="post-competition-analysis">Post-Competition Analysis</h2>
<p>After the competition was over, I decided to dig deeper into Random Forests, exploring differences in validation accuracy due to changes in parameters like <code>n_jobs</code> and <code>n_estimators</code>.</p>
<p>I ended up modeling and analyzing 960 Random Forests. You can see my whole process detailed in <a href="https://www.kaggle.com/code/vishalbakshi/post-competition-hyperparameter-sweep">this notebook</a>.</p>
<p>I chose 15 models out of 960 to submit to Kaggle post-competition in order to see their Private score, answering the question—should I have focused on tuning Random Forests instead of tuning an ensemble with a neural net?</p>
<p>The following table lists out my results. Here is a definition of the parameters I experimented with:</p>
<ul>
<li><code>n_jobs</code> = the number of processors used (<code>None</code> = 1 and <code>-1</code> = All)</li>
<li><code>n_estimators</code> = the number of trees included in the Random Forest</li>
<li><code>max_samples</code> = the number of randomly selected rows included for a tree</li>
<li><code>max_features</code> = the number of randomly selected columns included for a tree</li>
<li><code>min_samples_leaf</code> = the minimum samples allowed on a tree node</li>
<li><code>oob_score</code> = whether or not to use OOB score to evaluate a tree</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">n_jobs</th>
<th style="text-align: left;">n_estimators</th>
<th style="text-align: left;">max_samples</th>
<th style="text-align: left;">max_features</th>
<th style="text-align: left;">min_samples_leaf</th>
<th style="text-align: left;">oob_score</th>
<th style="text-align: left;">Private score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">10000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.89875*</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">15000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.89839</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">10000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.89803</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">80</td>
<td style="text-align: left;">15000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.89748</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">15000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.8973</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">5000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">5</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.89297</td>
</tr>
<tr class="odd">
<td style="text-align: left;">-1</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">10000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.89207</td>
</tr>
<tr class="even">
<td style="text-align: left;">-1</td>
<td style="text-align: left;">80</td>
<td style="text-align: left;">10000</td>
<td style="text-align: left;">0.5</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.89197</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">15000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.89143</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">80</td>
<td style="text-align: left;">10000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.89143</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">1000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.87165</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">1000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.87039</td>
</tr>
<tr class="odd">
<td style="text-align: left;">-1</td>
<td style="text-align: left;">40</td>
<td style="text-align: left;">1000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>False</code></td>
<td style="text-align: left;">0.86994</td>
</tr>
<tr class="even">
<td style="text-align: left;">-1</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">1000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.86768</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">1000</td>
<td style="text-align: left;"><code>None</code></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>True</code></td>
<td style="text-align: left;">0.86109</td>
</tr>
</tbody>
</table>
<p>*Top 65% in final leaderboard</p>
<hr>
<p>The best post-competition result with a single Random Forest I was able to get was a Private score of 0.89875 which would have landed me in the top 65% of the final leaderboard. Not the top 50% result I’m looking for this year, but significantly better than the top 83% result I got.</p>
<p>It’s tough to tell which parameters contributed to better Private scores, I would need a larger sample to work with, but it’s interesting to note that a <code>max_samples</code> value of 1000 did not crack the top 10 of the 15 models listed here. Similarly, an <code>n_estimators</code> value of 20 or a <code>min_samples_leaf</code> value of 10 did not get into the top 5. I had expected that setting <code>max_samples</code> “too high” or setting <code>min_samples_leaf</code> “too low” would overfit the Random Forest. But it seems like that is not the case. At least not for this competition with this test set.</p>
<p>I’ll also note that all of my submissions with a Private score of 0.89 or greater (live and post-competition) were single Random Forests, and all of them also had a Public score greater than 0.89.</p>
<p>I certainly don’t feel like I can make any solid claims with this analysis about Random Forests in general, but I can say that tuning Random Forest parameters is worth exploring in a Kaggle tabular competition.</p>
</section>
<section id="final-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="final-thoughts">Final Thoughts</h2>
<p>Almost every time I code something, I keep at the forefront of my mind the saying “make it work, make it right, make it fast” by Kent Beck. After this competition, I feel I landed somewhere between making it work and making it right. What is “right” when it comes to a competition? Well, at this stage of my machine learning journey, I would like to rank in the top 50% in the final Leaderboard. I was in the top 87% during the live competition, and in the top 65% post-competition, so I’m moving in the right direction.</p>
<p>I also want to take all of my learnings with a grain of salt. This was one (relatively small) dataset that certainly had its own problems (as I detailed in my <a href="https://www.kaggle.com/code/vishalbakshi/multi-class-prediction-of-obesity-risk-fastai#Understand-the-Data-Better">live competition notebook</a>) with one (relatively small) test set. Just because my neural net didn’t perform very well doesn’t indict all neural nets. Similarly, just because my single Random Forests performed well, doesn’t mean they always will. Also, just because the textbook’s Chapter 9 approach to tabular prediction didn’t result in a top Kaggle competition Private score, doesn’t mean it’s not immensibly valuable to data science in production.</p>
<p>At the end of this year, after hopefully competing in at least a couple more live competitions, I will look back at this experience as a necessary but insufficient step towards having good intuition about machine learning.</p>
<p>As always, I hope you enjoyed this blog post!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>